# ACN-Data API Tutorial (Fixed Authentication)

🟢 1️⃣ Install & Import (Colab Cell 1)

In [ ]:
!pip install requests pandas

import requests
import pandas as pd

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### 2. Enter API Token and Initialize Client
🟢 2️⃣ Set Token & Date Range (Colab Cell 2)

In [ ]:
# 🔐 Replace with your API token
TOKEN = "H3ivbHYg6LJxvzGV8oZzOLRtXXVjEogRRCBd91w08Wo"

BASE_URL = "https://ev.caltech.edu/api/v1/sessions/caltech"

params = {
    "where": 'connectionTime>="Tue, 1 Jan 2019 00:00:00 GMT" and connectionTime<="Fri, 1 Feb 2019 00:00:00 GMT"'
}

### 3. Fetch Data and Flatten Attributes
We will query for sessions at Caltech for the first week of September 2019. The script will use `pd.json_normalize()` to ensure that all nested JSON elements (like `userInputs`) are properly separated into individual columns.

In [ ]:
all_sessions = []

response = requests.get(BASE_URL, params=params, auth=(TOKEN, ''))
data = response.json()

all_sessions.extend(data["_items"])

# Pagination (25 sessions per page here)
while "_links" in data and "next" in data["_links"]:
    next_url = "https://ev.caltech.edu/api/v1/" + data["_links"]["next"]["href"]
    response = requests.get(next_url, auth=(TOKEN, ''))
    data = response.json()
    all_sessions.extend(data["_items"])

print("Total sessions retrieved:", len(all_sessions))

Total sessions retrieved: 985

In [ ]:
df = pd.json_normalize(all_sessions)

print("Shape:", df.shape)
df.head()

Shape: (985, 13)

,_id,userInputs,sessionID,stationID,spaceID,siteID,clusterID,connectionTime,disconnectTime,kWhDelivered,doneChargingTime,timezone,userID
0,5c3fda9df9af8b0d99c6fd60,"[{'userID': 489, 'milesRequested': 210, 'WhPer...",2_39_138_29_2019-01-01 03:45:49.452098,2-39-138-29,CA-304,0002,0039,"Tue, 01 Jan 2019 03:45:49 GMT","Tue, 01 Jan 2019 17:57:23 GMT",43.114,"Tue, 01 Jan 2019 10:40:45 GMT",America/Los_Angeles,000000489
1,5c3fda9df9af8b0d99c6fd61,"[{'userID': 1616, 'milesRequested': 20, 'WhPer...",2_39_130_31_2019-01-01 05:28:33.527740,2-39-130-31,CA-306,0002,0039,"Tue, 01 Jan 2019 05:28:34 GMT","Tue, 01 Jan 2019 06:03:12 GMT",3.250,"Tue, 01 Jan 2019 06:03:06 GMT",America/Los_Angeles,000001616
2,5c412c1df9af8b12cb56c27c,None,2_39_138_566_2019-01-01 17:41:44.784919,2-39-138-566,CA-512,0002,0039,"Tue, 01 Jan 2019 17:41:45 GMT","Tue, 01 Jan 2019 18:39:21 GMT",0.900,"Tue, 01 Jan 2019 18:40:21 GMT",America/Los_Angeles,None
3,5c412c1df9af8b12cb56c27d,"[{'userID': 558, 'milesRequested': 80, 'WhPerM...",2_39_79_379_2019-01-01 18:09:16.991864,2-39-79-379,CA-327,0002,0039,"Tue, 01 Jan 2019 18:09:17 GMT","Wed, 02 Jan 2019 02:39:32 GMT",12.534,"Tue, 01 Jan 2019 20:16:10 GMT",America/Los_Angeles,000000558
4,5c412c1df9af8b12cb56c27e,None,2_39_138_566_2019-01-01 18:39:24.566872,2-39-138-566,CA-512,0002,0039,"Tue, 01 Jan 2019 18:39:25 GMT","Tue, 01 Jan 2019 19:18:49 GMT",0.883,"Tue, 01 Jan 2019 19:19:47 GMT",America/Los_Angeles,None

In [ ]:
df_sessions = pd.json_normalize(all_sessions)

print("Shape:", df_sessions.shape)
df_sessions.head()

Shape: (985, 13)

,_id,userInputs,sessionID,stationID,spaceID,siteID,clusterID,connectionTime,disconnectTime,kWhDelivered,doneChargingTime,timezone,userID
0,5c3fda9df9af8b0d99c6fd60,"[{'userID': 489, 'milesRequested': 210, 'WhPer...",2_39_138_29_2019-01-01 03:45:49.452098,2-39-138-29,CA-304,0002,0039,"Tue, 01 Jan 2019 03:45:49 GMT","Tue, 01 Jan 2019 17:57:23 GMT",43.114,"Tue, 01 Jan 2019 10:40:45 GMT",America/Los_Angeles,000000489
1,5c3fda9df9af8b0d99c6fd61,"[{'userID': 1616, 'milesRequested': 20, 'WhPer...",2_39_130_31_2019-01-01 05:28:33.527740,2-39-130-31,CA-306,0002,0039,"Tue, 01 Jan 2019 05:28:34 GMT","Tue, 01 Jan 2019 06:03:12 GMT",3.250,"Tue, 01 Jan 2019 06:03:06 GMT",America/Los_Angeles,000001616
2,5c412c1df9af8b12cb56c27c,None,2_39_138_566_2019-01-01 17:41:44.784919,2-39-138-566,CA-512,0002,0039,"Tue, 01 Jan 2019 17:41:45 GMT","Tue, 01 Jan 2019 18:39:21 GMT",0.900,"Tue, 01 Jan 2019 18:40:21 GMT",America/Los_Angeles,None
3,5c412c1df9af8b12cb56c27d,"[{'userID': 558, 'milesRequested': 80, 'WhPerM...",2_39_79_379_2019-01-01 18:09:16.991864,2-39-79-379,CA-327,0002,0039,"Tue, 01 Jan 2019 18:09:17 GMT","Wed, 02 Jan 2019 02:39:32 GMT",12.534,"Tue, 01 Jan 2019 20:16:10 GMT",America/Los_Angeles,000000558
4,5c412c1df9af8b12cb56c27e,None,2_39_138_566_2019-01-01 18:39:24.566872,2-39-138-566,CA-512,0002,0039,"Tue, 01 Jan 2019 18:39:25 GMT","Tue, 01 Jan 2019 19:18:49 GMT",0.883,"Tue, 01 Jan 2019 19:19:47 GMT",America/Los_Angeles,None

In [ ]:
user_inputs_list = []

for session in all_sessions:
    if "userInputs" in session and session["userInputs"]:
        for ui in session["userInputs"]:
            ui["sessionID"] = session["sessionID"]
            user_inputs_list.append(ui)

df_user_inputs = pd.DataFrame(user_inputs_list)

print("User Inputs Shape:", df_user_inputs.shape)
df_user_inputs.head()

User Inputs Shape: (1083, 9)

,userID,milesRequested,WhPerMile,minutesAvailable,modifiedAt,paymentRequired,requestedDeparture,kWhRequested,sessionID
0,489,210,475,629,"Tue, 01 Jan 2019 03:47:45 GMT",True,"Tue, 01 Jan 2019 14:14:49 GMT",99.75,2_39_138_29_2019-01-01 03:45:49.452098
1,489,210,475,641,"Tue, 01 Jan 2019 03:50:27 GMT",True,"Tue, 01 Jan 2019 14:26:49 GMT",99.75,2_39_138_29_2019-01-01 03:45:49.452098
2,1616,20,400,60,"Tue, 01 Jan 2019 05:30:01 GMT",True,"Tue, 01 Jan 2019 06:28:34 GMT",8.00,2_39_130_31_2019-01-01 05:28:33.527740
3,558,80,222,514,"Tue, 01 Jan 2019 18:09:19 GMT",True,"Wed, 02 Jan 2019 02:43:17 GMT",17.76,2_39_79_379_2019-01-01 18:09:16.991864
4,1135,50,400,282,"Tue, 01 Jan 2019 21:06:08 GMT",True,"Wed, 02 Jan 2019 01:47:57 GMT",20.00,2_39_79_378_2019-01-01 21:05:56.972890

In [ ]:
df.to_csv("acn_timeseries_jan1_to_feb1_2019.csv", index=False)

In [ ]:
from google.colab import files
files.download("acn_timeseries_jan1_to_feb1_2019.csv")